stages:
  - build
  - deploy

variables:
  REGISTRY_IMAGE: registry.example.com/hello-nginx

build:
  stage: build
  script:
    - docker build -t $REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  script:
    - export KUBECONFIG=$(terraform output -raw kubeconfig)
    - helmfile -e $CI_ENVIRONMENT_NAME apply
