pipeline {
  agent any

  environment {
    REGISTRY_IMAGE = "registry.example.com/hello-nginx"
    ENVIRONMENT = "dev" // Cambiar a 'stage' si se desea
  }

  stages {
    stage('Build Docker Image') {
      steps {
        script {
          sh "docker build -t ${REGISTRY_IMAGE}:${env.BUILD_ID} ."
          sh "docker push ${REGISTRY_IMAGE}:${env.BUILD_ID}"
        }
      }
    }

    stage('Terraform Init') {
      steps {
        dir('infra/terraform/eks') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Apply') {
      steps {
        dir('infra/terraform/eks') {
          sh 'terraform apply -auto-approve'
        }
      }
    }

    stage('Helmfile Deploy') {
      steps {
        dir('deploy') {
          script {
            sh 'export KUBECONFIG=$(terraform -chdir=../infra/terraform/eks output -raw kubeconfig)'
            sh "helmfile -e ${ENVIRONMENT} apply"
          }
        }
      }
    }
  }
}
